meta_name: "Rückmal"
meta_title: "Rückmal - for a world free of backpain"
meta_description: "Rückmal is a holistic desktop app that enables & incentivises users via pop-up reminders, performance statistics, daily challenges, video content and more."
meta_image: "rueckmal-logo-1200.png"
